# -*- coding: utf-8 -*-
"""tensores .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABGyPz23qppRLeMf8UsZFQpYCLK_CNZt

**Instancaiar Tensores **
"""

import torch

lista = [[1,2,3],
         [4,5,6]]
tns = torch.tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)


tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

"""**Outras formas de instanciar Tensores**"""

import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
tns

tns0 = torch.zeros(4,5)
tns1 = torch.ones(2,3)
tns2 = torch.randn(3,3)
print(tns0)
print(tns1)
print(tns2)

arr = tns.data.numpy()
print(type(arr))
type(tns2)

"""**Operações com tensores**"""

tns = tns2[0:2, :]
print(tns)
print(tns1)

print('')
print(tns1 * tns)

print('')
print(tns1+tns)

print('')
print(torch.mm(tns1,tns.T))

"""**Funções .size() e .view()**"""

print(tns1.size())
print('')
print(tns1.view(3,2))
print('')
print(tns1)

print('')

tnst = torch.randn(2,2,3)
print(tnst)
print('')
tnst=tnst.view(12)
print(tnst)

"""**GPU CAST**"""

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)