# -*- coding: utf-8 -*-
"""RAG_AULA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPgScJ7gP0OWPwWRjpLIZyGfjY8rb-TY
"""

!pip install langchain langchain-google-genai pypdf
!pip install langchain-community

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('APY_RAG')

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

llm = ChatGoogleGenerativeAI(model='gemini-2.5-flash', temperature= 0)

#EXEMPLO 01: PROMPTING TRADICIONAL (SEM RAG)
pergunta = 'Qual é a política de home office de nossa empresa?'

prompt_tradicional = ChatPromptTemplate.from_template(
    'Responda a seguinte pergunta: {pergunta}'
)

chain_tradicional = prompt_tradicional | llm

resposta_tradicional = chain_tradicional.invoke({'pergunta': pergunta})
print(resposta_tradicional.content)