# -*- coding: utf-8 -*-
"""RAG_AULA05_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18b4WFlu9SDwdZ1vhijRUGqxJgIfk1WXc
"""

!pip install langchain langchain_google_genai langchain_community chromadb tiktoken google_generativeai ragas langsmith datasets

# Importações necessárias
import os
import pandas as pd
import numpy as np
from datetime import datetime
import json
import time
import warnings
warnings.filterwarnings('ignore')

# LangChain imports
'''
At the moment, updates are being implemented in the ConversationalRetrievalChain.
Therefore, depending on when you are reviewing this code, it may already be outdated.
I recommend consulting the official documentation for the most up-to-date guidance and implementation details.

'''
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferWindowMemory
from langchain.vectorstores import Chroma
from langchain.google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain.schema import Document
from langchain.text_splitter import CharacterTextSplitter

# RAGAS imports
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall
)

from datasets import Dataset

# Criação de documentos de exemplo sobre IA e tecnologia
#Creating sample documents about AI and technology.
documentos_conhecimento = [
    """Inteligência Artificial (IA) é um campo da ciência da computação que se concentra
na criação de sistemas capazes de realizar tarefas que normalmente requerem inteligência humana.
Isso inclui aprendizado, raciocínio, percepção e tomada de decisões. A IA pode ser classificada
em IA fraca (específica para tarefas) e IA forte (inteligência geral).""",
    """Machine Learning é uma subárea da IA que permite que computadores aprendam e melhorem
automaticamente através da experiência, sem serem explicitamente programados.
Os algoritmos de ML identificam padrões em dados e fazem previsões. Existem três tipos principais:
aprendizado supervisionado, não supervisionado e por reforço.""",
    """Deep Learning é uma técnica de machine learning baseada em redes neurais artificiais
com múltiplas camadas. É especialmente eficaz para tarefas como reconhecimento de imagem,
processamento de linguagem natural e reconhecimento de voz. As redes neurais profundas
podem ter centenas de camadas e milhões de parâmetros.""",
    """RAG (Retrieval-Augmented Generation) é uma técnica que combina recuperação de informações
com geração de texto. Permite que modelos de linguagem acessem conhecimento externo
para gerar respostas mais precisas e atualizadas. O processo envolve buscar documentos
relevantes e usar essas informações para gerar a resposta final.""",
    """Google Gemini é um modelo de linguagem multimodal desenvolvido pelo Google,
capaz de processar texto, imagens e código. Oferece capacidades avançadas de
raciocínio e compreensão contextual. O Gemini vem em diferentes versões:
Nano, Pro e Ultra, cada uma otimizada para diferentes casos de uso.""",
    """LangChain é um framework para desenvolvimento de aplicações com modelos de linguagem.
Facilita a criação de cadeias complexas, gerenciamento de memória e integração
com diferentes fontes de dados. Oferece componentes modulares para construir
aplicações robustas de IA conversacional."""
]



# Conversão para objetos Document
#Conversion to Document objects
docs = [Document(page_content=doc) for doc in documentos_conhecimento]
print(f"✅ Criados {len(docs)} documentos de conhecimento")

# Criação de dataset de teste para avaliação RAGAS
#Creating a test dataset for RAGAS evaluation.
dados_teste = {
    'question': [
        "O que é Inteligência Artificial?",
        "Como funciona o Machine Learning?",
        "Quais são as aplicações do Deep Learning?",
        "O que é RAG e como funciona?",
        "Quais são as características do Google Gemini?"
    ],
    'ground_truth': [
        "Inteligência Artificial é um campo da ciência da computação focado na criação de sistemas que realizam tarefas que requerem inteligência humana, como aprendizado, raciocínio e percepção.",
        "Machine Learning permite que computadores aprendam automaticamente através da experiência, identificando padrões em dados para fazer previsões.",
        "Deep Learning é eficaz para reconhecimento de imagem, processamento de linguagem natural e reconhecimento de voz, usando redes neurais profundas.",
        "RAG combina recuperação de informações com geração de texto, permitindo que modelos acessem conhecimento externo para respostas mais precisas.",
        "Google Gemini é um modelo multimodal que processa texto, imagens e código, oferecendo capacidades avançadas de raciocínio e vem em versões como Nano, Pro e Ultra."
    ]
}
print("✅ Dataset de teste criado!")
print(f"✅ {len(dados_teste['question'])} perguntas de teste preparadas")

# Inicializacao dos embeddings do Google Gemini
embeddings = GoogleGenerativeAIEmbeddings(
    model="models/embedding-001",
    google_api_key=GOOGLE_API_KEY
)

# Criação do vector store
vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory="./chroma_db_avaliacao"
)

# Configuracao da memória
memory= ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=3,
    return_messages=True,
    output_key='answer'
)

# Criação da cadeira RAG
rag_chain = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=vectorstore.as_retriever(search_kwargs={"k": 3}),
    memory=memory,
    return_source_documents=True,
    verbose=False
)