# -*- coding: utf-8 -*-
"""RAG_AULA 07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16h677Mclh8TliHEoDcCs3G6eqsDY8SPn
"""

!pip install langchain langchain-google-genai langchain_community faiss-cpu rank_bm25

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('APY_RAG')

from langchain_core.documents import Document
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

# Componentes principais
llm = ChatGoogleGenerativeAI(model="gemini-1.5-pro-latest", temperature=0)
embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

# Documentos de exemplo para os testes
docs = [ # Lista de documentos de conhecimento
    Document(page_content="O erro HTTP 404 Not Found indica que o servidor não conseguiu encontrar o recurso solicitado. Verifique a URL.", metadata={"source":"doc_erros_http"}),
    Document(page_content="O protocolo SSH (Secure Shell) é usado para acesso remoto seguro a servidores. A porta padrão é a 22.", metadata={"source":"doc_protocolos_rede"}),
    Document(page_content="Para listar contêineres Docker, use o comando 'docker ps'. O erro 'Cannot connect to the Docker daemon' significa que o serviço do Docker não está em execução.", metadata={"source":"doc_docker"}),
    Document(page_content="A política de férias da empresa permite 30 dias de descanso remunerado por ano. Para solicitar, acesse o portal de RH e preencha o formulário 'FRM-01-FERIAS'.", metadata={"source":"doc_politicas_rh"})
]

from langchain_community.retrievers import BM25Retriever
from langchain.retrievers import EnsembleRetriever
from langchain_community.vectorstores import FAISS

# Retriever de palavra-chave (Esparso)
bm25_retriever = BM25Retriever.from_documents(docs)
bm25_retriever.k = 2

# Retriever Vetorial (Denso)
faiss_vectorstore = FAISS.from_documents(docs, embeddings)
faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# Ensemble Retriever
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever],
    weights=[0.5, 0.5]
)

query_keyword = "Como peço férias usando o formulário FRM-01-FERIAS?"

print(f"--- Buscando por '{query_keyword}' --- \n")

# Busca apenas vetorial
print("--- Resultado da busca vetorial (FAISS) ---")
doc_faiss = faiss_retriever.invoke(query_keyword)
for doc in doc_faiss:
    print(f"-- {doc.page_content}")

# Busca Híbrida
print("\n--- Resultado da busca híbrida (EnsembleRetriever) ---")
doc_ensemble = ensemble_retriever.invoke(query_keyword)
for doc in doc_ensemble:
    print(f"-- {doc.page_content}")

# --- Teste de Recuperação ---
query_keyword = "Como peço férias usando o formulário FRM-01-FERIAS?"

def show_results(titulo, docs, termo="FRM-01-FERIAS"):
    print(f"\n--- {titulo} ---")
    for i, d in enumerate(docs, 1):
        src = d.metadata.get("source", "sem_source")
        print(f'{i} src="{src}" | {d.page_content[:120]}...') # desconente se quiser ver o início do texto

print(f"--- Buscando por: '{query_keyword}' ---")

# Busca vetorial (FAISS)
docs_faiss = faiss_retriever.invoke(query_keyword)
show_results("Resultados da busca vetorial (FAISS)", docs_faiss)

# Busca híbrida (BM25 + FAISS via EnsembleRetriever)
docs_ensemble = ensemble_retriever.invoke(query_keyword)
show_results("Resultados da busca híbrida (EnsembleRetriever)", docs_ensemble)

# Análise automática simples
faiss_top = docs_faiss[0].metadata.get("source")
ensemble_top = docs_ensemble[0].metadata.get("source")